name: Build

on:
  push:
    branches:
      - "master"
    tags:
      - "!*" # not a tag push
  pull_request:
    branches:
      - master

jobs:
  build-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet run --project ./src/Blog2/Blog2.csproj -c Release -- .